# 389. Find the Difference

# Easy

# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one
# more letter at a random position.

# Return the letter that was added to t.


# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"


# Constraints:
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.

from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        c = dict(Counter(t))
        for l in s:
            c[l] -= 1
            if c[l] == 0:
                del c[l]
        return list(c.keys())[0]

    def findTheDifference2(self, s: str, t: str) -> str:
        return (Counter(t) - Counter(s)).most_common(1)[0][0]


s = Solution()
s.findTheDifference2("abcd", "abcde")